### ISSUE TITLE
Verify that tests in Contile CI workflow are working as expected 🕵🏻 

### ISSUE THREAD

**Issue by hackebrot** [mozilla-services/contile-integration-tests#33]
- [x] Check that the integration tests run against cached Contile Docker image from the `build` job
 - [x] Submit a pull request with a code change in Contile that would fail the integration tests and see if an error is reported
 - [x] Check that the pytest assertion error messages for failed tests contain actionable information
 - [x] Check that the `contile-integration-tests` job runs for every pull request
 - [x] Check that the `contile-integration-tests` job runs for push to the `main` branch
 - [x] Check that the `contile-integration-tests` job blocks the `deploy` job

**Comment by hackebrot** [comment]
#### Check that the integration tests run against cached Contile Docker image from the `build` job

We can see in the [integration test docker-compose.yml][docker-compose.yml] that the image `app:build` is used. ✅ 

#### Submit a pull request with a code change in Contile that would fail the integration tests and see if an error is reported

My [pull request which introduced a bug to contile][pull_request_bug] failed with the expected error message. ✅ 

#### Check that the pytest assertion error messages for failed tests contain actionable information

When a test fails because the status code of the response from contile doesn't match what is specified in the scenario step, we don't provide additional information from the response. This may be useful for debugging the issue. 🚧 

#### Check that the `contile-integration-tests` job runs for every pull request

We can see that there are no filters defined for the [contile-integration-tests][integration_test_job] Circle CI job. ✅ 

Here's an example pull request where the integration tests ran: https://github.com/mozilla-services/contile/pull/229/checks?check_run_id=3203943226

#### Check that the `contile-integration-tests` job runs for push to the `main` branch

We can see that there are no filters defined for the [contile-integration-tests][integration_test_job] Circle CI job. ✅ 

#### Check that the `contile-integration-tests` job blocks the `deploy` job

This is not the case. Currently the `deploy` job only depends on `build` and `test`. 🚧 

[docker-compose.yml]: https://github.com/mozilla-services/contile/blob/main/docker-compose.yml#L18
[pull_request_bug]: https://github.com/mozilla-services/contile/pull/227
[integration_test_job]: https://github.com/mozilla-services/contile/blob/main/.circleci/config.yml#L230

**Comment by hackebrot** [comment]
#### Check that the `contile-integration-tests` job blocks the `deploy` job

We have merged a pull request in Contile to block the `deploy` job on integration tests. ✅ 

For example the CI pipeline for this pull request reflects that change https://github.com/mozilla-services/contile/pull/240

**Comment by hackebrot** [comment]
#### Check that the pytest assertion error messages for failed tests contain actionable information

We have merged a pull request in Contile (see https://github.com/mozilla-services/contile/pull/241) to use the **21.3.0** Docker images which contain the changes from #50. ✅ 

You can observe the improved error reporting in the CI logs of this pull request https://github.com/mozilla-services/contile/pull/227/checks?check_run_id=3259626698

**Comment by hackebrot** [comment]
Hi @ashrivastava-qa! 👋🏻 I think we're ready to close this issue as completed. Anything else that we should verify?

**Comment by ashrivastava-qa** [comment]
Yes all the items looks completed to me. We can close this out. Thanks!

**Comment by ashrivastava-qa** [comment]
This has been completed, hence closing the issue.
